apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  labels: {}
  name: "jenkins"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "jenkins"
    name: "jenkins"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - name: "http"
      port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "jenkins"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "jenkins"
    name: "jenkins-jnlp"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - name: "agent"
      port: 50000
      protocol: "TCP"
      targetPort: 50000
    selector:
      project: "jenkins"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    labels:
      project: "jenkins"
    name: "jenkins"
  spec:
    replicas: 1
    selector:
      project: "jenkins"
    template:
      metadata:
        labels:
          project: "jenkins"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "JENKINS_PASSWORD"
            value: "${JENKINS_PASSWORD}"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/jenkins-openshift-pipeline:latest"
          name: "jenkins"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 50000
            name: "agent"
          - containerPort: 8080
            name: "http"
        imagePullSecrets: []
        nodeSelector: {}
        serviceAccountName: "jenkins"
parameters:
- description: "Jenkins admin password"
  name: "JENKINS_PASSWORD"
  value: "admin"
